### ISSUE TITLE
Error after update to Flutter 3.29

### ISSUE THREAD

**Issue by amedeopro** [harrowmykel/disk_space_plus#6]
How can i solve it ?

e: file:///Users/xxxx/.pub-cache/hosted/pub.dev/disk_space_plus-0.2.4/android/src/main/kotlin/com/piccmaq/disk_space_plus/DiskSpacePlusPlugin.kt:15:48 Unresolved reference: Registrar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':disk_space_plus:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3m 27s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by adnandogar** [comment]
just fork and fix or use existing forks

**Comment by rovshan-b** [comment]
If anyone knows about existing fork please suggest.

**Comment by rocboronat** [comment]
Which fork do you recommend? There are many. Just out of curiosity, I checked if there's one from you, but nope.

This issue is also breaking our builds on Flutter 3.29.1.

**Comment by amedeopro** [comment]
@rocboronat 

```
  disk_space_plus:
    git:
        url: https://github.com/Tooltopia/disk_space_forked
        ref: a41cc2f
```

enjoy!
